<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Zend Framework Quickstart</title>
  <?php echo $this->headLink()->appendStylesheet('/QuickStart/public/css/global.css') ?>
</head>
<body>

<?php echo $this->navigation(); ?>

<p>
Voce esta em: <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(1)->render(); ?>
</p>

<?php echo $this->layout()->content ?>

</body>
</html>