<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Zend Framework Quickstart</title>
  <?php echo $this->headLink()->appendStylesheet('/QuickStart/public/css/global.css') ?>
</head>
<body>

<div id="nav">
  <?php echo $this->navigation(); ?>
</div>

<div id="breadcrumb">
  Você esta em: <?php echo $this->navigation()->breadcrumbs()->setLinkLast(true)->setMinDepth(0)->render(); ?>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>